"""Source-first arXiv HTML extraction.

arXiv HTML (generated by LaTeXML) preserves the semantic structure the PDF
loses: sections, paragraphs, figures, tables, math, citations. When the
HTML exists it becomes the primary source: sections come from <section>
trees, paragraphs from ltx_para, figure/table/caption bindings are native,
and citation callouts link to bibliography entries directly.

The output uses the shared Block model; blocks carry
metadata["source_kind"]="ARXIV_HTML" and
metadata["html_role"] for provenance.
"""

from __future__ import annotations

import hashlib
import re
from typing import Any

from lxml import etree
from lxml import html as lxml_html

from .models import Block, BlockType
from .net import make_arxiv_httpx_client

ARXIV_HTML_URL = "https://arxiv.org/html/{arxiv_id}"
# LaTeXML HTML embeds the arXiv distribution license as the first paragraph
_LICENSE_RE = re.compile(
    r"permission is hereby granted|arXiv\.org perpetual license|"
    r"distribute this Work|grants permission to reproduce the (?:tables|figures)",
    re.IGNORECASE,
)


def fetch_arxiv_html(arxiv_id: str, *, timeout: float = 30.0) -> str:

    headers = {
        "User-Agent": "Mozilla/5.0 (PaperLens/2.0; academic reader)",
        "Accept": "text/html,application/xhtml+xml",
    }
    last_error: Exception | None = None
    for _attempt in range(3):
        try:
            with make_arxiv_httpx_client(  # 仅 arXiv 走加速代理（V3.7）
                timeout=timeout, follow_redirects=True, headers=headers
            ) as client:
                response = client.get(ARXIV_HTML_URL.format(arxiv_id=arxiv_id))
                response.raise_for_status()
                return response.text
        except Exception as exc:  # noqa: BLE001 - transient TLS/network, retry
            last_error = exc
    raise last_error or RuntimeError("arXiv HTML fetch failed")


def _clean_text(raw: str) -> str:
    return re.sub(r"\s+", " ", raw).strip()


def _node_text_with_math(node: Any, *, skip_latex: set[str] | None = None) -> str:
    """Itertext with <math> nodes replaced by their LaTeX alttext (V3.12).

    Without this, inline formulas leak MathML rendering text ("AP 50
    subscript AP 50 ...") into paragraphs; display formulas listed in
    ``skip_latex`` are excluded from the paragraph text entirely (they get
    their own FORMULA blocks).

    V3.21: inline latex is wrapped in ``$...$`` — the translation layer
    already protects ``$...$`` spans (MATH_INLINE_RE) and the frontend uses
    the same delimiters to render inline math with KaTeX.
    """
    skip_latex = skip_latex or set()
    parts: list[str] = []

    def walk(element: Any) -> None:
        if not isinstance(element.tag, str):  # comments / processing
            return
        # V3.21b：display 公式表格（ltx_equation）整体不进段落文本——
        # 它已由解析器抽成独立 FORMULA 块，连编号 "(1)" 也不该混入正文
        if "ltx_equation" in " ".join(element.get("class", "").split()):
            if element.tail:
                parts.append(element.tail)
            return
        if element.tag == "math":
            latex = element.get("alttext") or ""
            if latex and latex not in skip_latex:
                parts.append(f"${latex}$")
            if element.tail:
                parts.append(element.tail)  # 公式编号 "(1)" 等尾部文本
            return  # do not descend into MathML markup
        if element.tag in ("script", "style"):
            return
        if element.text:
            parts.append(element.text)
        for child in element:
            walk(child)
        if element.tail:
            parts.append(element.tail)

    walk(node)
    return _clean_text(" ".join(parts))


def _equation_latex_and_number(element: Any) -> tuple[str, str]:
    """Display 公式容器（tr/div.ltx_equation）里取首个 math 的 alttext 与编号。

    LaTeXML 结构：<tr class="ltx_equation"><td class="ltx_eqn_cell"><math
    alttext="..."/></td><td class="ltx_eqn_cell ltx_eqn_number"><span
    class="ltx_tag">(1)</span></td></tr>（V3.21b）
    """
    latex = ""
    math = element.xpath(".//math")
    if math:
        latex = math[0].get("alttext") or ""
    number = ""
    for tag in element.xpath(
        ".//span[contains(@class,'ltx_tag')] | .//td[contains(@class,'ltx_eqn_number')]"
    ):
        number_match = re.search(r"\((\d+(?:\.\d+)?)\)", "".join(tag.itertext()))
        if number_match:
            number = number_match.group(1)
            break
    return latex, number


_AUTHOR_SEPARATOR_RE = re.compile(r"\s+and\s+|\s*,\s*")
_VENUE_STARTS = (
    "arxiv preprint",
    "arxiv:",
    "corr",
    "in ",
    "proceedings of",
    "journal",
    "ieee",
    "lecture notes",
    "advances in",
    "transactions on",
)
# tokens strong enough to mark venue anywhere in the block (a plain "in "
# also occurs inside titles, so it is startswith-only)
_VENUE_CONTAINS = (
    "corr",
    "arxiv",
    "proceedings",
    "ieee",
    "springer",
    "lecture notes",
    "advances in neural",
    "transactions",
    "conference on",
    "neurips",
    "iclr",
    "icml",
    "cvpr",
    "eccv",
    "acl",
    "emnlp",
    "naacl",
    "nips",
)


def _is_author_block(text: str) -> bool:
    """True if a ltx_bibblock is an author list (mostly capitalized words).

    LaTeXML emits one ltx_bibblock per semantic field ;
    author lists are almost entirely capitalized name tokens, while titles
    and venue strings mix lowercase words and punctuation. A short block of
    fully capitalized words ("John Smith.") is also a name list.
    """
    if len(text) > 200:
        return False
    words = re.findall(r"[A-Za-z]+", text)
    if not words:
        return False
    capitalized = sum(1 for word in words if word[:1].isupper())
    if capitalized / len(words) < 0.65:
        return False
    return bool(re.search(r"\sand\s", text) or "," in text) or all(
        word[:1].isupper() for word in words
    )


def _is_venue_block(text: str) -> bool:
    """True if a ltx_bibblock is venue / journal / arXiv id material."""
    lowered = text.lower()
    if any(lowered.startswith(marker) for marker in _VENUE_STARTS):
        return True
    # a trailing year alone is not enough: "title, 2001." (Hochreiter) stays a
    # title; the year marks venue only when venue material appears in the body
    if re.search(r"\b(19|20)\d{2}\b\s*[.)]?\s*$", text):
        body = re.sub(r",?\s*\d{4}\s*[.)]?\s*$", "", text).lower()
        return any(marker in body for marker in _VENUE_CONTAINS)
    return False


def _clean_author_parts(parts: list[str]) -> list[str]:
    """Strip split debris (", and" prefixes) from author name parts."""
    cleaned: list[str] = []
    for part in parts:
        part = part.strip()
        part = re.sub(r"^(?:and|&)\s+", "", part).strip()
        if part:
            cleaned.append(part.rstrip("."))
    return cleaned[:8]


def _split_bib_blocks(blocks: list[str]) -> tuple[list[str], str, str]:
    """Classify ltx_bibblock segments into (authors, title, venue).

    Standard order is authors -> title -> venue. Venue-like blocks never
    become titles; the quoted-title regex remains a fallback for non-LaTeXML
    markup (used by parse_bibliography below).
    """
    authors: list[str] = []
    title = ""
    venue = ""
    for block in blocks:
        if not block:
            continue
        if not authors and _is_author_block(block):
            authors = _clean_author_parts(_AUTHOR_SEPARATOR_RE.split(block))
            continue
        if not venue and _is_venue_block(block):
            venue = block
            continue
        if not title:
            # strip a trailing ", 2001." that LaTeXML sometimes folds into the
            # title block; the year is extracted separately from the raw text
            title = re.sub(r",?\s*\d{4}\s*[.)]?\s*$", "", block).strip()
    return authors, title, venue


def parse_bibliography(html_text: str, *, version_id: str = "") -> list[dict[str, object]]:
    """Extract bibliography entries from LaTeXML's ltx_biblist.

    Each <li id="bib.bibN"> holds one entry; the entry's citation key maps
    to the <cite> anchors in the body. Authors / title / venue come from the
    ltx_bibblock segments (DOM structure, ); when markup is
    absent, IEEE-style quoted titles are used as a fallback. Fields stay
    best-effort: the raw text is preserved and online resolution
    (Crossref/arXiv) provides identity.

    Reference IDs follow the app-wide convention ``ref-{version_id[:10]}-{n}``
    (same as callouts and the PDF path) so callout->entry binding works; when
    version_id is empty (direct call), a deterministic local id is used.
    """
    from .models import ReferenceIdentity, ReferenceRecord

    tree = lxml_html.fromstring(html_text)
    entries: list[dict[str, object]] = []
    bib_list = tree.xpath("//ul[contains(@class, 'ltx_biblist')]")
    if not bib_list:
        return []
    prefix = version_id[:10] if version_id else "html"
    items = bib_list[0].xpath(".//li[contains(@class, 'ltx_bibitem')]")
    for index, item in enumerate(items, start=1):
        raw = _clean_text("".join(item.itertext()))
        if not raw:
            continue
        # LaTeXML 的 ltx_tag 提供 "[n]"，bibblock 开头又常带 "n "——
        # 双重序号只保留一个（前端已渲染 sequence_number，fix 2026-08-04）
        raw = re.sub(r"^\[\d+\]\s*", "", raw)
        raw = re.sub(r"^\d+\s*", "", raw)
        # 与 PDF 路径的 YEAR_RE 同款：年份不得后跟 ".数字"（arXiv 编号/
        # DOI 里的 4 位数字不得误抓为年份）
        year_match = re.search(r"(?<!\d)(?:18|19|20)\d{2}(?!\d|\.\d)", raw)
        blocks = [
            _clean_text("".join(block.itertext()))
            for block in item.xpath(".//span[contains(@class, 'ltx_bibblock')]")
        ]
        authors, title, venue = _split_bib_blocks(blocks)
        title_match = re.search(r'"([^"]+)"', raw)
        if not title and title_match:
            title = title_match.group(1)
        if not authors:
            # IEEE fallback: names sit between the leading "[n]" and the title;
            # the number prefix is optional because the display raw_text has
            # already been cleaned of its duplicate numbering (fix 2026-08-04)
            number_prefix = re.match(r"(?:\[?\d+\]?\s*)?", raw)
            author_end = title_match.start() if title_match else len(raw)
            author_text = raw[number_prefix.end() : author_end]
            authors = _clean_author_parts(_AUTHOR_SEPARATOR_RE.split(author_text))
        # V4.8（题目要求③）：与 PDF 路径一致地提取 DOI / arXiv 编号，
        # 否则 lint 会把 "arXiv preprint arXiv:2411.00001" 等误报为
        # REF_BAD_ARXIV_ID / REF_BAD_DOI（字段未解析出）
        from .references import extract_arxiv_id, extract_doi

        entries.append(
            ReferenceRecord(
                reference_id=f"ref-{prefix}-{index}",
                raw_text=raw,
                sequence_number=index,
                parsed_title=title,
                authors=authors,
                year=int(year_match.group(0)) if year_match else None,
                venue=venue,
                identity_status=ReferenceIdentity.UNRESOLVED,
                doi=extract_doi(raw),
                arxiv_id=extract_arxiv_id(raw),
            )
        )
    # V4.8（题目要求③）：HTML 路径同样做格式检查（风格感知 lint），
    # 此前只有 PDF 路径检查
    from .references import lint_references

    return [
        record.model_dump(mode="json")
        for record in lint_references(entries)
    ]


def extract_metadata(html_text: str) -> dict[str, str]:
    """Title / authors / abstract from the LaTeXML header (arXiv-style).

    : the workbench header shows these like arXiv HTML —
    centered title, author line, abstract block.
    """
    tree = lxml_html.fromstring(html_text)
    title = ""
    headings = tree.xpath("//h1[contains(@class, 'ltx_title')]") or tree.xpath("//h1")
    if headings:
        title = _clean_text("".join(headings[0].itertext()))
    authors_nodes = tree.xpath("//div[contains(@class, 'ltx_authors')]")
    authors = ""
    if authors_nodes:
        authors = _clean_text("".join(authors_nodes[0].itertext()))
        # strip affiliation/funding boilerplate after the last name-like "and"
        authors = re.split(r"(?i)\bthis work was supported\b", authors)[0].strip()
    abstract_nodes = tree.xpath("//*[contains(@class, 'ltx_abstract')]")
    abstract = ""
    if abstract_nodes:
        abstract = _clean_text("".join(abstract_nodes[0].itertext()))
        abstract = re.sub(r"^(abstract)\s*:?\s*", "", abstract, flags=re.IGNORECASE).strip()
    return {"title": title, "authors": authors, "abstract": abstract}


def extract_assets(html_text: str, *, arxiv_id: str) -> list[dict[str, object]]:
    """Figure/table assets from the LaTeXML DOM.

    Figures carry real image URLs in arXiv HTML (x1.png relative to the
    paper's HTML path) — no client-side PDF cropping needed. Tables get a
    record with their caption; structured HTML rendering is a later step.
    """
    from .documents import AssetExtractionStatus, AssetKind, AssetSourceKind

    tree = lxml_html.fromstring(html_text)
    base = f"https://arxiv.org/html/{arxiv_id}/"
    assets: list[dict[str, object]] = []

    for index, figure in enumerate(tree.xpath("//figure[contains(@class, 'ltx_figure')]"), start=1):
        caption = _clean_text(" ".join(figure.xpath(".//figcaption//text()")))
        images = figure.xpath(".//img")
        src = ""
        for image in images:
            candidate = image.get("src") or image.get("data-src") or ""
            if candidate:
                if candidate.startswith("http"):
                    src = candidate
                else:
                    # V3.23：img src 的第一段就是版本目录
                    #（"1706.03762v7/Figures/ModalNet-21.png"），完整路径
                    # 拼到 /html/ 下即可（arXiv 页面资源相对重定向后的
                    # 版本 URL 解析）。此前只取文件名拼根路径全部 404
                    first = candidate.split("/")[0]
                    if re.match(rf"^{re.escape(arxiv_id)}v\d+$", first):
                        src = f"https://arxiv.org/html/{candidate.lstrip('/')}"
                    else:
                        src = base + candidate.lstrip("/")
                break
        assets.append(
            {
                "asset_id": f"fig-html-{index:02d}",
                "asset_kind": AssetKind.FIGURE.value,
                "page": 1,
                "bbox": [0.0, 0.0, 0.0, 0.0],
                "caption_original": caption,
                "caption_translation": "",
                "content_uri": src,
                "source_kind": AssetSourceKind.EMBEDDED_RASTER.value,
                "confidence": 0.9,
                "extraction_status": AssetExtractionStatus.EXTRACTED.value,
            }
        )

    from .tables import expand_cells_to_grid, rows_to_csv

    for index, table in enumerate(
        tree.xpath(
            "//figure[contains(@class, 'ltx_table')] | //table[contains(@class, 'ltx_tabular')]"
        ),
        start=1,
    ):
        caption = _clean_text(
            " ".join(
                table.xpath(".//*[contains(@class, 'ltx_caption')]//text()")
            )
        )
        # 结构化表格：LaTeXML <tr>/<td> 直接
        # 转 cell matrix + CSV，前端渲染真实表格并可一键下载
        raw_rows: list[list[dict[str, object]]] = []
        for tr in table.xpath(".//tr"):
            cells: list[dict[str, object]] = []
            for cell in tr.xpath("./td | ./th"):
                cells.append(
                    {
                        "text": _clean_text(" ".join(cell.itertext())),
                        "rowspan": int(cell.get("rowspan", "1") or "1"),
                        "colspan": int(cell.get("colspan", "1") or "1"),
                    }
                )
            if cells:
                raw_rows.append(cells)
        structured: dict[str, object] = {}
        if raw_rows:
            grid = expand_cells_to_grid(raw_rows)
            structured = {
                "rows": grid,
                "csv": rows_to_csv(grid),
                "html": _table_rows_to_html(grid),
            }
        assets.append(
            {
                "asset_id": f"tab-html-{index:02d}",
                "asset_kind": AssetKind.TABLE.value,
                "page": 1,
                "bbox": [0.0, 0.0, 0.0, 0.0],
                "caption_original": caption,
                "caption_translation": "",
                "content_uri": "",
                "source_kind": AssetSourceKind.STRUCTURED_TABLE.value,
                "structured_data": structured or None,
                "confidence": 0.9 if structured else 0.5,
                "extraction_status": (
                    AssetExtractionStatus.EXTRACTED.value
                    if structured
                    else AssetExtractionStatus.PARTIAL.value
                ),
            }
        )
    return assets


def _table_rows_to_html(grid: list[list[str]]) -> str:
    """Grid -> minimal <table> markup for inline rendering (V3.12)."""
    if not grid:
        return ""
    lines = ["<table>"]
    for row_index, row in enumerate(grid):
        tag = "th" if row_index == 0 else "td"
        lines.append(
            "<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in row) + "</tr>"
        )
    lines.append("</table>")
    return "".join(lines)


def parse_arxiv_html(html_text: str, *, arxiv_id: str) -> list[Block]:
    """Parse arXiv HTML into Blocks with full section/paragraph/media order.

    Reading order is the DOM order of the document body: sections and their
    paragraphs, interspersed with figures, tables and formulas, exactly like
    the paper reads. Each block carries an ascending ``html_index``.
    """
    tree = lxml_html.fromstring(html_text)
    blocks: list[Block] = []
    sha = hashlib.sha256(html_text.encode("utf-8")).hexdigest()
    paper_id = sha[:16]

    def add(
        text: str,
        *,
        role: str,
        section_path: str = "",
        bbox: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0),
        formula_number: str = "",
    ) -> None:
        text = _clean_text(text)
        if not text:
            return
        metadata: dict[str, object] = {
            "page_width": 0.0,
            "page_height": 0.0,
            "source_kind": "ARXIV_HTML",
            "html_logical": True,
            "html_role": role,
            "html_section": section_path,
        }
        # V3.21：display 公式编号（"(1)" 尾部）入库，前端 arXiv 风格
        # 右侧对齐显示；PDF 路径已在 jobs.py 写同一字段
        if formula_number:
            metadata["formula_number"] = formula_number
        blocks.append(
            Block(
                block_id=f"html-{paper_id}-{len(blocks):05d}",
                paper_id=paper_id,
                # V4.1：解析阶段 paper_version_id 未知，to_blocks 以 version 补全
                paper_version_id="",
                page=1,  # HTML has no physical pages; logical order only
                block_index=len(blocks),
                bbox=bbox,
                block_type=BlockType.TEXT,
                text=text,
                content_sha256=hashlib.sha256(text.encode("utf-8")).hexdigest(),
                metadata=metadata,
            )
        )

    def parse_figure(node: Any, section_path: str) -> None:
        caption = node.xpath(".//figcaption//text()")
        if caption:
            # 空格 join 与 extract_assets 保持一致：此前 "".join 产生
            # "Figure 1: ..."，资产 caption 是 "Figure 1 : ..."，前端
            # caption↔资产匹配全失败 → 图没插入正文（fix 2026-08-04）
            add(" ".join(caption), role="CAPTION", section_path=section_path)
        else:
            add("(figure without caption)", role="FIGURE", section_path=section_path)

    def parse_table(node: Any, section_path: str) -> None:
        caption = node.xpath(".//caption//text()")
        caption = caption or node.xpath(".//*[contains(@class,'ltx_caption')]//text()")
        # 空格 join 与 extract_assets 保持一致（图 caption 已修，表漏了——
        # "".join 与 " ".join 差异导致表格资产与 caption 块匹配失败，
        # 结构化表格无法内联，fix 2026-08-04）
        add(" ".join(caption) if caption else "(table)", role="TABLE", section_path=section_path)

    def walk(node: Any, section_path: str) -> None:
        if not isinstance(node.tag, str):  # comments / processing instructions
            return
        tag = etree.QName(node).localname
        classes = " ".join(node.get("class", "").split())

        # V3.21b：display 公式的 LaTeXML 表格结构（tr/div.ltx_equation >
        # td.ltx_eqn_cell > math + 编号单元格）。此前的检测只认 p 的直接
        # math 子节点，Attention Is All You Need 等论文的公式全部漏掉。
        if "ltx_equation" in classes:
            latex, number = _equation_latex_and_number(node)
            if latex:
                add(
                    latex,
                    role="FORMULA",
                    section_path=section_path,
                    formula_number=number,
                )
            return

        if "ltx_bibliography" in classes:
            return  # bibliography lives in parse_bibliography(), not body blocks

        if tag == "section" and "ltx_section" in classes:
            heading = node.xpath(".//h2 | .//h3 | .//h4")
            heading_text = _clean_text("".join(heading[0].itertext())) if heading else ""
            if heading_text:
                add(heading_text, role="HEADING", section_path=section_path)
            new_path = f"{section_path} > {heading_text}" if heading_text else section_path
            for child in node:
                walk(child, new_path)
            return

        if tag == "figure" and "ltx_figure" in classes:
            parse_figure(node, section_path)
            return
        if tag == "figure" and "ltx_table" in classes:
            # 表格 wrapper 是 <figure class="ltx_table">（figcaption 在 wrapper 上）：
            # 此前只处理内部 <table>，caption 取不到 → "(table)" 占位 →
            # 与资产 caption 匹配失败 → 表格永不内联（fix 2026-08-04）
            parse_table(node, section_path)
            return
        if tag == "table" and ("ltx_table" in classes or "ltx_tabular" in classes):
            parse_table(node, section_path)
            return

        if "ltx_abstract" in classes:
            # 摘要进入正文流（V3.8）：此前 ltx_abstract 不是 ltx_para 被 walk
            # 跳过 → 摘要只在展示 header 里，不翻译、不进检索
            text = "".join(node.itertext())
            if text.strip():
                add(text, role="PARAGRAPH", section_path="Abstract")
            return

        if tag == "div" and "ltx_para" in classes:
            # 公式提取：
            # - inline math 在段落内，用 alttext（LaTeX）替换 MathML 渲染文本
            # - display math（p 级独立 <math>）提取为 FORMULA 块
            display_formulas: list[tuple[str, str]] = []  # (latex, number)
            for p_node in node.xpath("./p"):
                math_nodes = p_node.xpath("./math")
                if len(math_nodes) != 1:
                    continue
                latex = math_nodes[0].get("alttext") or ""
                if not latex:
                    continue
                # p 里除该公式外没有其他文本 → 独立 display 公式；
                # 尾部公式编号 "(1)" 不算正文，编号捕获入库（V3.21）
                rest = _node_text_with_math(p_node, skip_latex={latex})
                if not rest or re.fullmatch(r"\(\d+(?:\.\d+)?\)", rest):
                    number = ""
                    if rest:
                        number_match = re.match(r"\((\d+(?:\.\d+)?)\)", rest)
                        number = number_match.group(1) if number_match else ""
                    display_formulas.append((latex, number))
            # V3.21b：LaTeXML 的 display 公式也可能以表格结构嵌在段落内
            # （tr.ltx_equation），同样抽出为 FORMULA 块并从段落文本排除
            nested_formulas: list[tuple[str, str]] = []
            for equation in node.xpath(
                ".//*[contains(concat(' ', normalize-space(@class), ' '), ' ltx_equation ')]"
            ):
                # table 和 tr 都带 ltx_equation 类：只取最外层容器，避免重复
                if equation.xpath(
                    "ancestor::*[contains(concat(' ', normalize-space(@class), ' '), ' ltx_equation ')]"
                ):
                    continue
                latex, number = _equation_latex_and_number(equation)
                if latex:
                    nested_formulas.append((latex, number))
            all_formulas = display_formulas + nested_formulas
            text = _node_text_with_math(
                node, skip_latex={item[0] for item in all_formulas}
            )
            if _LICENSE_RE.search(text):
                return  # license boilerplate is not part of the paper
            add(text, role="PARAGRAPH", section_path=section_path)
            for latex, number in all_formulas:
                add(
                    latex,
                    role="FORMULA",
                    section_path=section_path,
                    formula_number=number,
                )
            return

        for child in node:
            walk(child, section_path)

    body = tree.find(".//body")
    if body is not None:
        walk(body, "")
    return blocks
